# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphwidget = QtWidgets.QWidget(self.centralwidget)
        self.graphwidget.setGeometry(QtCore.QRect(0, 10, 421, 401))
        self.graphwidget.setObjectName("graphwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(433, 10, 341, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.varList = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.varList.setContentsMargins(0, 0, 0, 0)
        self.varList.setObjectName("varList")
        self.varLayout_1 = QtWidgets.QHBoxLayout()
        self.varLayout_1.setObjectName("varLayout_1")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.varLayout_1.addWidget(self.label)
        self.varInput_1 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.varInput_1.setObjectName("varInput_1")
        self.varLayout_1.addWidget(self.varInput_1)
        self.varList.addLayout(self.varLayout_1)
        self.varLayout_2 = QtWidgets.QHBoxLayout()
        self.varLayout_2.setObjectName("varLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.varLayout_2.addWidget(self.label_2)
        self.varInput_2 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.varInput_2.setObjectName("varInput_2")
        self.varLayout_2.addWidget(self.varInput_2)
        self.varList.addLayout(self.varLayout_2)
        self.varLayout_3 = QtWidgets.QHBoxLayout()
        self.varLayout_3.setObjectName("varLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.varLayout_3.addWidget(self.label_3)
        self.varInput_3 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.varInput_3.setObjectName("varInput_3")
        self.varLayout_3.addWidget(self.varInput_3)
        self.varList.addLayout(self.varLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Var1"))
        self.label_2.setText(_translate("MainWindow", "Var2"))
        self.label_3.setText(_translate("MainWindow", "Var3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
