# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphwidget = QtWidgets.QWidget(self.centralwidget)
        self.graphwidget.setGeometry(QtCore.QRect(0, 10, 541, 401))
        self.graphwidget.setObjectName("graphwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(553, 10, 221, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.varList = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.varList.setContentsMargins(0, 0, 0, 0)
        self.varList.setObjectName("varList")
        self.layout_1 = QtWidgets.QHBoxLayout()
        self.layout_1.setObjectName("layout_1")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.layout_1.addWidget(self.label)
        self.input_u = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.input_u.setObjectName("input_u")
        self.layout_1.addWidget(self.input_u)
        self.varList.addLayout(self.layout_1)
        self.layout_2 = QtWidgets.QHBoxLayout()
        self.layout_2.setObjectName("layout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.layout_2.addWidget(self.label_2)
        self.input_v = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.input_v.setObjectName("input_v")
        self.layout_2.addWidget(self.input_v)
        self.varList.addLayout(self.layout_2)
        self.layout_3 = QtWidgets.QHBoxLayout()
        self.layout_3.setObjectName("layout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.layout_3.addWidget(self.label_3)
        self.input_w = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.input_w.setObjectName("input_w")
        self.layout_3.addWidget(self.input_w)
        self.varList.addLayout(self.layout_3)
        self.calcbutton = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget)
        self.calcbutton.setObjectName("calcbutton")
        self.varList.addWidget(self.calcbutton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "U"))
        self.label_2.setText(_translate("MainWindow", "V"))
        self.label_3.setText(_translate("MainWindow", "W"))
        self.calcbutton.setText(_translate("MainWindow", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
